name: Publish ASP.NET Core with Angular to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Angular build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Angular dependencies and build
      - name: Install Angular dependencies
        run: 
          cd ./server/apiplate/clientApp &&
          npm install
      - name: Set NODE_OPTIONS
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
        shell: bash
      # Step 4: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Adjust the .NET version as needed

      - name: Build with dotnet 
        run: 
          cd ./server/apiplate &&
          dotnet build  --configuration Release
  
      - name: dotnet publish
        run: 
          cd ./server/apiplate &&
          dotnet publish   -c Release -o "${{env.DOTNET_ROOT}}/publish"

      # Step 6: Deploy to FTP server
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish # Directory containing the published files
          server-dir: /wwwroot # Adjust the target directory on your FTP server
